### ISSUE TITLE
[BUG] not working anymore

### ISSUE THREAD

**Issue by gudge25** [richardadonnell/Upwork-Job-Scraper#107]
this error apears  on load
**Error loading pairs: getAllPairs is not defined**

and WebHook URL disappear

**Comment by richardadonnell** [comment]
Hi @gudge25 

Thank you for this feedback!

Unfortunately, I pushed a broken update (v1.59.6) which was causing this error. Luckily, I caught the issue right away, and it should be fixed now. Just make sure you are running the latest version (v1.59.10), which should be available in the Chrome Web Store, here: https://chromewebstore.google.com/detail/upwork-job-scraper-+-webh/mojpfejnpifdgjjknalhghclnaifnjkg?hl=en&authuser=0 or you can manually download the ZIP and load the unpacked extension manually, here: https://github.com/richardadonnell/Upwork-Job-Scraper/releases/tag/1.59.10

Hope this helps! Please let me know if you have any issues!

R

**Comment by gudge25** [comment]
@richardadonnell  thanks for reply
what i did  - remove addon from chrome  
re-add it from Chrome Web Store
i still cant see webhook URL + error appears on start

![Image](https://github.com/user-attachments/assets/e74d6457-65a6-4871-a3f9-a6d375918fcc)

**Comment by richardadonnell** [comment]
Hi @gudge25 

If you go to the [Chrome Web Store extension page](https://chromewebstore.google.com/detail/upwork-job-scraper-+-webh/mojpfejnpifdgjjknalhghclnaifnjkg?hl=en&authuser=0), which version do you see?

![Image](https://github.com/user-attachments/assets/4f1b0ead-5230-41a8-a0d8-f1b03c9eadb1)

This issue should be resolved in version 1.59.10. Otherwise, you can grab the [v1.59.10 ZIP here](https://github.com/richardadonnell/Upwork-Job-Scraper/releases/tag/1.59.10) and try manually install the unpacked extension.

**Comment by gudge25** [comment]
hi
Details
Version
1.59.10

**Comment by richardadonnell** [comment]
Sorry for the delay @gudge25 - I recently started a new job, AND my development workstation at home just decided to completely break itself, requiring a complete format and OS reinstall.

I'll try to give this some attention this week!

**Comment by richardadonnell** [comment]
Hi @gudge25 

Thanks again for your patience. I've been working on resolving the issues you encountered.

The `"Error loading pairs: getAllPairs is not defined"` error typically indicates a problem with the communication between the settings page and the extension's background script. I've implemented several improvements in version `1.59.11` to make this connection more robust and handle potential initialization delays better. This should hopefully prevent that specific error from occurring.

Version `1.59.11` isn't released just yet, but I'm hoping to get it out soon after some final checks. I'll update this issue once it's available on the Chrome Web Store.

Thank you for your patience - apologies again for the delay!
